import type { Metadata } from "next";
import "./globals.css";

import { GlobalProvider } from "@/context/globalContext";
import { Toaster } from "react-hot-toast";
import { CookiesProvider } from "next-client-cookies/server";
import { Barlow, Oswald, Ruslan_Display } from "next/font/google";
import ReduxClientProvider from "@/helpers/ReduxClientProvider";

const body = Barlow({
  display: "swap",
  variable: "--font-body",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const heading = Ruslan_Display({
  display: "swap",
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${body.variable} ${heading.variable}`}>
      <body>
        <CookiesProvider>
          <ReduxClientProvider>
            <GlobalProvider>
              <Toaster position="bottom-center" />
              {children}
            </GlobalProvider>
          </ReduxClientProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
